### ISSUE TITLE
Query parameters

### ISSUE THREAD

**Issue by stefanledin** [jyokum/healthgraph#1]
Hi! 
I get the 25 latest activities from the user by doing this:

``` php
$hgc->getIterator('GetFitnessActivityFeed')->setLimit(25);
```

But I would like to do something like this instead:
`/fitnessActivities?noEarlierThan=2011-03-01`
(http://developer.runkeeper.com/healthgraph/example-api-calls#example-get-time-scope)
Is there any way to include these parameters in the query?

**Comment by jyokum** [comment]
You can pass in parameters as a second argument to getIterator or getCommand

$hgc->getIterator('GetFitnessActivityFeed', array("noEarlierThan" => "2011-03-01"));

**Comment by stefanledin** [comment]
Nice! Thanks :)
